version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: conway_technical
      POSTGRES_PASSWORD: password
      POSTGRES_DB: conway_technical
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://conway_technical:password@postgres/conway_technical
      REDIS_URL: redis://redis:6379
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app

  frontend:
    build: ./frontend
    environment:
      PUBLIC_API_URL: http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: